name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Docker Image
        run: docker build -t aniket626630/reactjs-app .
        
      - name: Publish image to docker hub
        run: docker push aniket626630/reactjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted  # This should be the self-hosted runner on your EC2 instance
    steps:
      - name: Pull image from docker hub
        run: docker pull aniket626630/reactjs-app:latest
        
      - name: Delete Old Container
        run: docker rm -f reactContainer || true  # Ignore error if container doesn't exist
        
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer aniket626630/reactjs-app:latest
